### ISSUE TITLE
Upgrade spark 

### ISSUE THREAD

**Issue by jmlero** [bigboards/bb-stack-training#1]
Hi,

We are using the HEX board with this stack which is what we need, but the spark version installed is 1.4
We would like to use the version 1.6. How should we proceed in order to upgrade the version? Could you update or create a new docker image. Also we would like to use some python packages. Could those packages be included?
Thanks.

**Comment by wimvanleuven** [comment]
Hello,

The stack deploys spark via Docker images build from https://github.com/bigboards/docker-spark/blob/master/Dockerfile. We can simply upgrade this to the required version. Versioning is still a bit of an issue. We are discussing how to deal with them in the Hive, without having to build docker images for all combinations from different github repos.

The stack deploys Spark on Yarn, meaning that all code gets run on the yarn worker nodes. So, to install additional packages, we can easily include them in the hadoop images. Have a look at the docker file here https://github.com/bigboards/docker-hadoop/blob/master/Dockerfile which already includes pip numpy scipy pandas scikit-learn matplotlib. If others are required, we can simply add them there. 

If you changes these dockerfiles in the respective repositories and commit them, our build farm will roll out new docker images including those changes. 

Do test the stack though as a lot of others depend on these images.
